[versions]
agp = "8.5.0"
brainxsdk = "2.1.0.3"
constraintlayout = "2.1.4"
glide = "4.16.0"
kotlin = "1.9.0"

[libraries]
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
brainxsdk = { module = "tech.brainx.sdk:brainxsdk", version.ref = "brainxsdk" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

